### PR TITLE
Add myself with elm-graph and elm-intdict

### PR DESCRIPTION
**Pull request by sgraf812**
I'd like to register https://github.com/sgraf812/elm-graph and https://github.com/sgraf812/elm-intdict.

Is this how you do it? What additional steps do I have to take?

### CODE REVIEW

**Comment by rgrempel** [comment]
Do you mean that you'd like to move those two repositories into the elm-community organization? If so, could you say a little bit more about why you want to do that?

Just to back up a bit, the maintainers file is for repositories that are already in the elm-community organization -- it's not a general mechanism for indicating who maintains **all** Elm packages.

My apologies if I've misunderstood what you want.

**Comment by sgraf812** [comment]
> why you want to do that?

I realized that I didn't do much Elm recently and probably won't be doing in the foreseeable future. I was thinking that by moving my repositories here, there are basically more people with collaborator access and there might even be a future maintainer around here.

Note that I don't just want to dump my projects here to get off duty, I just want to make sure that someone is there with access to my repository if I got hit by a bus.

I probably misunderstood what this organization is for, so you could just close this and I'll leave it as it is.

**Comment by rgrempel** [comment]
Ah, actually that is more or less exactly what elm-community is for. Or, at least one of the things it is for.

And, those libraries look very interesting -- they certainly deserve a good home.

So, I could do the process of moving them to elm-community if you like. That basically means forking it into elm-community, adding you as a collaborator, and then re-publishing into the elm-package system.

Now, one of the things we've been doing lately is removing the "elm-" prefix from things in elm-community, since here it's a little redundant (it makes more sense in personal repositories). So, the new repositories would be `elm-community/graph` and `elm-community/intdict`. Does that make sense to you?

The other question when "adopting" repositories is how to deal with the version history when republishing the package in Elm's package system. One method (somewhat easier) is to delete all the existing tags and start over at version 1.0.0. The other method is to re-publish each tag in order, preserving the version history and the current version number (a little tedious, but not that bad, really). Do you have a preference as far as that goes?

I'll cc: @mgold in case I've forgotten anything about how adopting a package goes ... I think he's done it more recently than I have.

**Comment by sgraf812** [comment]
I already adopted said naming scheme in the PR and would gladly redo the versioning stuff (keeping the history of tags and republish them, that is).

**Comment by rgrempel** [comment]
Super!

I've forked and renamed the repositories, and invited you to be a "collaborator" with admin rights to them.

I think you should be able to take things from there re: re-publishing them ... as I noted above, the trick is either to delete the existing tags and start over at 1.0.0, or keep the existing tags, check out each version in turn (starting with 1.0.0), and publishing each of them. (I suppose you would probably have to use Elm 0.16 to publish earlier versions and then Elm 0.17 to publish the latest).

Let me know if there's anything else I can do.

**Comment by sgraf812** [comment]
Finally came around to do this. I went with option 2, just republishing the packages as 1.0.0.

Republishing all versions would mean to rewrite history etc., because I'd have to change elm-package.json for each release.

**Pull request merged**
