### PR TITLE
Adding myself as maintainer to a new project called Elm Canvas

### PR DESCRIPTION
**Pull request by Chadtech**
Hey folks!

Im working to make the canvas API accessible within Elm. Im happy to work on this on my own, but I know Im not the first person to think about an Elm Canvas module, and I would love to get feedback on how to manage this project.

### CODE REVIEW

**Comment by mgold** [comment]
Hey there!

`elm-community` emerged to steward important packages where the original maintainer was absent, and this maintainers file is a way to make sure packages have new maintainers. There are plenty of useful and respected packages published by their authors under their own GitHub name, so that's what you should do!

As for how to manage the project, you can ask on the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss) and people will be happy to give you suggestions. I don't have much beyond "write tests" and "batch breaking changes".

Good luck with your canvas library, but you don't need to add yourself here.

**Comment by Chadtech** [comment]
Sounds good! That makes sense to me. Thanks for the consideration at least. For whatever its worth, eeue56 in the elm-community slack suggested I make this PR.

**Comment by mgold** [comment]
Yeah, I just saw that and I'm quite confused. What's going on Noah @eeue56?

**Comment by eeue56** [comment]
@Chadtech said that they wished to have community guidence and input, messaging elm-community. That's why I suggested they post here. It's worth noting that the sole purpose of elm-community is _not_ to maintain old repos. It's also to collectively work on new problems, e.g elm-webgl 2.x, elm-test 2.x, and so on

**Comment by jvoigtlaender** [comment]
@eeue56, that's all fine, but the PR here was to add an entry for repository https://github.com/Chadtech/elm-canvas to `maintainers.md`, whereas all other repositories in that maintainer list are (so far, and I think on purpose) repositories living under https://github.com/elm-community.

**Comment by eeue56** [comment]
Usually when we open these prs, that's when the repo is moved pr created here. regardless, I have no opinion - I just pointed chadtech here instead of the slack channel where they want unanswered

**Comment by Chadtech** [comment]
Im obviously not the one who can say what Elm-Community is about, but I would like to corroborate and elaborate on what @eeue56 said. 

Unlike every other Elm project Ive ever worked on, I looked into getting Elm-Canvas in Elm-Community for the following two reasons:

0 An Elm-Canvas API has been in the back of a lot of minds for quite a while now. In the last year Ive talked to people about such a package on the google group and on slack. At an Elm NYC meet up I showed off some code from another developer who made a cool canvas drawing app in Elm (using ports). Even in the readme of Evan's Elm-Graphics he says he expects that one day theyll be a canvas API. Since a lot of people are interested in this, and since the Elm Community unites around singular packages, collaboration and visibility are a priority.

1 I would really love to hear other peoples ideas on how to make an Elm-Canvas package. I have a lot of experience with the canvas element, and I have my own ideas on how to make an API for it, but Im sure other people have better ideas. The package that I am making will ultimately be better with more input.

So those are just my thoughts. If you all figure my Canvas project isnt something that belongs in Elm-Community it wont hurt my feelings.  I figure I should give a comprehensive explanation before the topic is dropped.

**Comment by jvoigtlaender** [comment]
I do think that would be a great thing to do, and I am very happy that you are willing to lead the effort! But if it's to be an elm-community effort, it should take place in a repository https://github.com/elm-community/canvas, not https://github.com/Chadtech/elm-canvas as indicated in your PR. That's really all I was aiming at.

**Pull request closed without merging**
