### PR TITLE
Have rtfeldman maintain elm-test

### PR DESCRIPTION
**Pull request by rtfeldman**
I discussed this with @eeue56 - I've been doing a ton of work on elm-test lately and am happy to assume responsibility for it.

### CODE REVIEW

**Comment by eeue56** [comment]
Vs @elm-community/owners

**Comment by Apanatshka** [comment]
@rtfeldman I've added you as a collaborator with write access. I've left @eeue56's write access intact, because I don't know if you had some PR/review process in mind.

**Comment by Apanatshka** [comment]
And apparently I didn't check enough of my messages because you're an owner now, so you could have done that yourself ^^

**Comment by mgold** [comment]
I added him as an owner maybe 12 hour ago.

**Pull request merged**
