### PR TITLE
Updated myself as a maintainer to the github page

### PR DESCRIPTION
**Pull request by maraisr**

### CODE REVIEW

**Comment by jaapz** [comment]
This has been here for a while now, shouldn't it be merged?

**Comment by maraisr** [comment]
Sure - @jaapz

**Comment by eeue56** [comment]
Not sure if this is really needed. What would maintaince of it involve?

**Comment by maraisr** [comment]
Yeah - sorry for trying to be involved.

**Comment by eeue56** [comment]
@maraisr That's not the point here. We're always looking for new maintainers for things, but I'm just not sure what maintaining this repo will involve - it's not really used for anything at the moment.

**Pull request closed without merging**
