### PR TITLE
Add @prikhi as html-extra Maintainer

### PR DESCRIPTION
**Pull request by prikhi**
I would like to take over maintenance of the html-extra package.

Not sure if there are necessary qualifications, but I have a couple Elm projects under my belt & am pretty active on Slack:
https://github.com/Southern-Exposure-Seed-Exchange/Order-Manager-Prototypes/tree/master/elm/
https://github.com/prikhi/bodyweight-client
https://github.com/prikhi/RSSonate

Let me know if you'd like any more information.

### CODE REVIEW

**Comment by prikhi** [comment]
Do I need to do anything else to get write access to the repo?

**Comment by mgold** [comment]
I've added you to our group and team. It should "just work" once you accept the invitation.

**Comment by prikhi** [comment]
Looks like the packages team only has read access to html-extra.

**Comment by mgold** [comment]
That's odd. Fixed.

**Pull request merged**
