### PR TITLE
Maintain list-extra, maybe-extra, and result-extra

### PR DESCRIPTION
**Pull request by abadi199**
I would like to help maintaining elm-list-extra, elm-maybe-extra, and elm-result-extra.

### CODE REVIEW

**Comment by abadi199** [comment]
I'm currently still don't have write access to the above repos. Can someone please add my account as a  collaborator?

**Comment by jvoigtlaender** [comment]
I think this "someone" needs to be someone listed as "Owner" at https://github.com/orgs/elm-community/people.

**Comment by fredcy** [comment]
@rgrempel Are you the one for this?

**Comment by abadi199** [comment]
I believe @mgold and @Apanatshka are also "owner"

**Comment by rgrempel** [comment]
Thanks for the ping ... I've now added @abadi199 as a collaborator on those. Sorry for not seeing this earlier!

I've also added @jvoigtlaender as another owner, and created an @elm-community/owners group, so you can easily ping all of the "owners" at once if you like.

**Comment by abadi199** [comment]
Btw, I can't mention @elm-community/owners group, I think because it's a private group?

**Comment by mgold** [comment]
Huh, seems to work for me (as an owner). If the purpose of the group is to make the owners pingable, this is rather unfortunate.

**Comment by rgrempel** [comment]
I don't think it's a private group -- at least, I can't find the setting in the admin page that would make it more public. If anyone knows where the "let the team be mentioned by anyone" setting is, let me know!

**Comment by rgrempel** [comment]
Here's the options I see for team visibility ... it looks as though the most visible you can make a team is "mentionable by members of the organization" ... unless there is another setting I'm missing.

screen shot 2016-05-17 at 10 04 59 pm

**Comment by fredcy** [comment]
It works for me, a mere elm-community peon, to reference @elm-community/owners.

**Comment by abadi199** [comment]
I think it doesn't work for me because I'm not a member of elm-community organization. And based the settings @rgrempel posted, it's probably not possible to make that group visible by non member. 

I recommend just update the [README.md](https://github.com/elm-community/Manifesto/blob/master/README.md) to include list of all owners so people will know who to ping in case they need help from the owner.

**Pull request merged**
