### PR TITLE
Maintainer for html-test-runner

### PR DESCRIPTION
**Pull request by kofigumbs**
Had a chat with @rtfeldman in Slack about moving his package here. The repo doesn't exist yet though.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Done, and repo created: https://github.com/elm-community/html-test-runner

You should have admin access to it. Ping me when the next release is out, and I'll publish a new release of `rtfeldman/html-test-runner` deprecating it and pointing people here.

Thanks for taking it over!

**Comment by eeue56** [comment]
It's best to move the original repo to elm-community, then fork it back to the original owner. That way issues can be directed easily to the new repo. @hkgumbs, please see and complete this checklist:

- [ ] PR adding the new repository & maintainer to [maintainers.md](https://github.com/elm-community/Manifesto/blob/master/maintainers.md)
- [ ] Maintainer has been made an elm-community nember & part of maintainers group
- [ ] An `elm-community` repository has been created with the same name
- [ ] Original package owner has forked `elm-community` repo back to their account
- [ ] All Tags From the `elm-community` repository have been deleted
- [ ] Repository in elm-package.json has been changed & version Set to `1.0.0`
- [ ] New 1.0.0 tag has been added
- [ ] Elm-Community Package Has Been Published

**Comment by rtfeldman** [comment]
@eeue56 got it - in this case there's only 1 issue open (and 1 issue closed, which was a TODO for updating dependencies), so we're not really missing anything.

Happy to follow process anyway if you think it's better. Do you know if anything bad happens if we delete the existing repo and recreate it as a fork?

**Comment by eeue56** [comment]
Ideally, preferred. Makes tracking down a repo a little easier. But you shouldn't delete the repo, this is what you should do if you want to move it:

- Delete elm-community/html-test-runner
- Move rtfeldman/html-test-runner to elm-community
- Fork html-test-runner back to rtfeldman

**Comment by rtfeldman** [comment]
Sorry, yeah - that's the one I meant deleting. 😅 

Done!

**Pull request merged**
