### PR TITLE
Add myself as maintainer to existing project 'elm-combine'

### PR DESCRIPTION
**Pull request by stil4m**
Support unmaintained repository 'elm-combine' (#57).

### CODE REVIEW

**Comment by mgold** [comment]
Thanks for volunteering! I just sent you a request to join the org.

**Comment by eeue56** [comment]
- delete all the tags the repo currently has
- reset the elm-package.json file to 1.0.0
- make sure the elm-package.json points to elm-community/elm-combine
- publish as 1.0.0

**Comment by stil4m** [comment]
What about the name of the package. Should we rename it to `elm-community/combine` instead of `elm-community/elm-combine`? Or even to `elm-community/parser-combinator`?

**Comment by mgold** [comment]
`elm-community/parser-combinators` (note the plural) is my preference, but you're the maintainer, so I guess you make the decision. I or another admin will need to actually move the repo.

**Comment by stil4m** [comment]
`elm-community/parser-combinators` would be my pick. I assume that a user would search on either `parser` `parser combinators` `parser generator` when searching for a package like this. I believe a new name would be more appropriate. Could one of you change this?

**Comment by mgold** [comment]
Changed. I also removed all the git tags (`git tag | xargs git push origin -d`) and reset `elm-package.json`.

**Pull request merged**
